---
- name: Change Password
  hosts: workers

  # Setting
  #vars:
    #change_user: "rolroralra"
    #newpassword: "chrlghk123#"

  tasks:
  - name: Change Password
    user:
      name: "{{ target_user }}"
      update_password: always
      password: "{{ newpassword | password_hash('sha512') }}"
